-- migration: 0026_practice_cards
-- Active Knowledge Base MVP — practice-card store + refresh-run records.
-- Cards own structured/relational state here and are PROJECTED into memory_chunks
-- (source_type='practice_card') for ANN search, so we also widen the existing
-- memory_chunks source_type CHECK constraint to admit the new value.
-- Idempotent: safe to re-run. See Rollback block at the foot of the file.

-- ─── Widen memory_chunks source_type CHECK to include 'practice_card' ─────────
-- The constraint name is auto-generated by Postgres as <table>_<column>_check.
-- Drop-and-recreate is the only portable way to alter a CHECK in place.
ALTER TABLE memory_chunks DROP CONSTRAINT IF EXISTS memory_chunks_source_type_check;
ALTER TABLE memory_chunks
  ADD CONSTRAINT memory_chunks_source_type_check
  CHECK (source_type IN ('code','pipeline_run','document','memory_entry','practice_card'));

-- ─── practice_cards ───────────────────────────────────────────────────────────
-- status:       'active' | 'superseded' | 'deprecated'
-- review_state: 'pending_verification' | 'pending_review' | 'accepted' | 'rejected'
-- content_hash: sha256 over canonicalized(statement+rationale+applies_to) — SERVER
--               computed, used for idempotent upsert + diff. UNIQUE per workspace.
-- ingested_by / verified_by are the adversarial-curation provenance: a card must
-- be proposed and verified by DIFFERENT actors (enforced in the API layer).
-- ingested_by_user_id is NOT NULL: the verify gate's identity check depends on a
-- bound trusted ingester, so a card can never be persisted without one.

CREATE TABLE IF NOT EXISTS practice_cards (
  id                   VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id         VARCHAR NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  topic                TEXT NOT NULL,
  statement            TEXT NOT NULL,
  rationale            TEXT NOT NULL,
  applies_to           JSONB NOT NULL DEFAULT '{}',
  sources              JSONB NOT NULL DEFAULT '[]',
  confidence           REAL NOT NULL DEFAULT 0,
  status               TEXT NOT NULL DEFAULT 'active'
                         CHECK (status IN ('active','superseded','deprecated')),
  supersedes           JSONB NOT NULL DEFAULT '[]',
  superseded_by        JSONB NOT NULL DEFAULT '[]',
  ingested_by          TEXT NOT NULL,
  ingested_by_user_id  TEXT NOT NULL,
  verified_by          TEXT,
  verified_by_user_id  TEXT,
  verification         JSONB NOT NULL DEFAULT '{}',
  review_state         TEXT NOT NULL DEFAULT 'pending_verification'
                         CHECK (review_state IN ('pending_verification','pending_review','accepted','rejected')),
  content_hash         TEXT NOT NULL,
  last_verified_at     TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- HIGH security fix (defense-in-depth): re-assert NOT NULL on ingested_by_user_id
-- for any environment that applied an earlier nullable version of this migration.
-- Idempotent — a no-op when the column is already NOT NULL. Safe because the API
-- guard refuses ingest without a bound user id, so no null rows can exist.
ALTER TABLE practice_cards ALTER COLUMN ingested_by_user_id SET NOT NULL;

-- Idempotent upsert / dedupe key.
CREATE UNIQUE INDEX IF NOT EXISTS practice_cards_content_hash_uq
  ON practice_cards (workspace_id, content_hash);

CREATE INDEX IF NOT EXISTS practice_cards_workspace_topic_idx
  ON practice_cards (workspace_id, topic);

CREATE INDEX IF NOT EXISTS practice_cards_status_idx
  ON practice_cards (workspace_id, status);

CREATE INDEX IF NOT EXISTS practice_cards_review_state_idx
  ON practice_cards (workspace_id, review_state);

CREATE INDEX IF NOT EXISTS practice_cards_verified_idx
  ON practice_cards (workspace_id, last_verified_at);

-- ─── practice_card_refresh_runs ───────────────────────────────────────────────
-- Thin record so humans can review a refresh without re-running it.
-- The refresh loop writes findings here; it NEVER mutates cards (Wave 2).

CREATE TABLE IF NOT EXISTS practice_card_refresh_runs (
  id            VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id  VARCHAR NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  topic         TEXT NOT NULL,
  trigger       TEXT NOT NULL DEFAULT 'manual',
  status        TEXT NOT NULL DEFAULT 'running'
                  CHECK (status IN ('running','completed','failed')),
  report        JSONB NOT NULL DEFAULT '{}',
  started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS practice_card_refresh_runs_workspace_idx
  ON practice_card_refresh_runs (workspace_id);

-- Rollback:
--   ALTER TABLE practice_cards ALTER COLUMN ingested_by_user_id DROP NOT NULL;
--   DROP TABLE IF EXISTS practice_card_refresh_runs;
--   DROP TABLE IF EXISTS practice_cards;
--   ALTER TABLE memory_chunks DROP CONSTRAINT IF EXISTS memory_chunks_source_type_check;
--   ALTER TABLE memory_chunks
--     ADD CONSTRAINT memory_chunks_source_type_check
--     CHECK (source_type IN ('code','pipeline_run','document','memory_entry'));
