/**
 * Morning Brief — the personalized daily news board.
 *
 * Workspace-scoped (route /workspaces/:id/morning-brief). Two relevance-ordered
 * feeds (internal Omniscience + external curated news), an "Affects you" panel
 * (the headline, from blast_radius), per-item feedback controls, and a profile
 * editor. Lazily generated by the backend on first GET of the day.
 *
 * Workspace scoping: the :id route param is the workspace id; the workspace row
 * is fetched to obtain ownerId (for the refresh role gate) and the name. The
 * current user comes from useAuth() for role gating; the server stays the source
 * of truth for every gate.
 *
 * SECURITY: every brief-/Omniscience-/fetch-derived string rendered here flows
 * through child components as INERT React text only (no HTML sink). See
 * use-news.ts + the component headers. relevanceScore / impactScore are
 * system-derived signals.
 */
import { useMemo } from "react";
import { useRoute } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Radio, Globe, ShieldOff } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import type { WorkspaceRow } from "@shared/schema";
import { useBrief, useRefreshBrief, type NewsItem } from "@/hooks/use-news";
import { canRefresh, canEditProfile, feedItems } from "@/lib/news";
import { BriefHeader } from "@/components/news/BriefHeader";
import { FeedCard } from "@/components/news/FeedCard";
import { AffectsPanel } from "@/components/news/AffectsPanel";
import { ProfileEditor } from "@/components/news/ProfileEditor";
import {
  FeedSkeleton,
  QueryError,
  EmptyState,
  errorMessage,
} from "@/components/news/QueryStates";

function todayLocalISODate(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export default function MorningBrief() {
  const [, params] = useRoute<{ id: string }>("/workspaces/:id/morning-brief");
  const workspaceId = params?.id ?? "";
  const { user } = useAuth();
  const { toast } = useToast();

  const { data: workspace } = useQuery<WorkspaceRow>({
    queryKey: ["workspace", workspaceId],
    queryFn: () =>
      apiRequest("GET", `/api/workspaces/${workspaceId}`).then((r) => r.json()),
    enabled: !!workspaceId,
  });

  const { data, isLoading, isError, error, refetch } = useBrief(workspaceId);
  const refresh = useRefreshBrief(workspaceId);

  const ownerId = workspace?.ownerId ?? null;
  const refreshAllowed = canRefresh(user, ownerId);
  const editAllowed = canEditProfile(user);

  const brief = data?.brief;
  const items = useMemo<NewsItem[]>(() => data?.items ?? [], [data]);
  const internal = useMemo(() => feedItems(items, "internal"), [items]);
  const external = useMemo(() => feedItems(items, "external"), [items]);
  const internalDegraded = brief?.internalDegraded ?? false;

  function handleRefresh() {
    refresh.mutate(undefined, {
      onSuccess: () =>
        toast({
          title: "Refresh requested",
          description: "Your brief is regenerating — it will update here shortly.",
        }),
      onError: (err) =>
        toast({
          variant: "destructive",
          title: "Refresh failed to start",
          description: errorMessage(err),
        }),
    });
  }

  const date = brief?.briefDate ?? todayLocalISODate();

  return (
    <div className="flex h-full flex-col">
      <BriefHeader
        workspaceName={workspace?.name}
        brief={brief}
        date={date}
        canRefresh={refreshAllowed}
        isRefreshing={refresh.isPending}
        onRefresh={handleRefresh}
      />

      <div className="flex-1 overflow-auto p-6">
        {isError ? (
          <QueryError message={errorMessage(error)} onRetry={() => refetch()} />
        ) : (
          <div className="mx-auto grid max-w-6xl grid-cols-1 gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
            {/* ── Left column: the two feeds ── */}
            <div className="space-y-8">
              <FeedSection
                testId="internal-feed"
                icon={<Radio className="h-4 w-4" />}
                title="Internal"
                subtitle="What changed in your platform"
                loading={isLoading}
                items={internal}
                workspaceId={workspaceId}
                emptyTitle="No internal updates"
                emptyDescription="Nothing from your internal platform feed in today's window."
                degradedNote={internalDegraded ? <InternalDegradedNote /> : null}
              />

              <FeedSection
                testId="external-feed"
                icon={<Globe className="h-4 w-4" />}
                title="External"
                subtitle="Industry & vendor news"
                loading={isLoading}
                items={external}
                workspaceId={workspaceId}
                emptyTitle="No external news"
                emptyDescription="No curated external items matched your profile today."
              />
            </div>

            {/* ── Right column: headline + personalization ── */}
            <aside className="space-y-6 lg:sticky lg:top-0 lg:self-start">
              {isLoading ? (
                <FeedSkeleton rows={2} />
              ) : (
                <AffectsPanel items={internal} degraded={internalDegraded} />
              )}
              <ProfileEditor workspaceId={workspaceId} canEdit={editAllowed} />
            </aside>
          </div>
        )}
      </div>
    </div>
  );
}

interface FeedSectionProps {
  testId: string;
  icon: React.ReactNode;
  title: string;
  subtitle: string;
  loading: boolean;
  items: NewsItem[];
  workspaceId: string;
  emptyTitle: string;
  emptyDescription: string;
  degradedNote?: React.ReactNode;
}

function FeedSection({
  testId,
  icon,
  title,
  subtitle,
  loading,
  items,
  workspaceId,
  emptyTitle,
  emptyDescription,
  degradedNote,
}: FeedSectionProps) {
  return (
    <section aria-labelledby={`${testId}-heading`} data-testid={testId}>
      <header className="mb-3 flex items-baseline gap-2">
        <span className="text-muted-foreground">{icon}</span>
        <h2 id={`${testId}-heading`} className="text-lg font-semibold tracking-tight">
          {title}
        </h2>
        <span className="text-xs text-muted-foreground">{subtitle}</span>
        {!loading && (
          <span className="ml-auto text-xs tabular-nums text-muted-foreground">
            {items.length} item{items.length === 1 ? "" : "s"}
          </span>
        )}
      </header>

      {degradedNote}

      {loading ? (
        <FeedSkeleton />
      ) : items.length === 0 ? (
        <EmptyState icon={icon} title={emptyTitle} description={emptyDescription} />
      ) : (
        <div className="space-y-3">
          {items.map((item) => (
            <FeedCard key={item.id} workspaceId={workspaceId} item={item} />
          ))}
        </div>
      )}
    </section>
  );
}

/**
 * Internal-feed degraded note — a clear NON-error explanation that the internal
 * Omniscience feed is unavailable. Rendered as a note, never as an error state.
 */
function InternalDegradedNote() {
  return (
    <div
      className="mb-3 flex items-start gap-2 rounded-lg border border-border bg-muted/30 px-3 py-2 text-sm text-muted-foreground"
      role="note"
      data-testid="internal-feed-degraded"
    >
      <ShieldOff className="mt-0.5 h-4 w-4 shrink-0" />
      <p>
        Internal feed unavailable (Omniscience not configured). External news and
        your profile still work — internal platform updates and the
        &quot;affects you&quot; signal will appear once Omniscience is connected.
      </p>
    </div>
  );
}
