{{- if and .Values.authToken (not .Values.existingAuthSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abox.authSecretName" . }}
  labels:
    {{- include "abox.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.authSecretKey }}: {{ .Values.authToken | b64enc | quote }}
{{- end }}
