{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multiqlti.fullname" . }}
  labels:
    {{- include "multiqlti.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ (.Values.secrets.jwtSecret | default (randAlphaNum 64)) | b64enc | quote }}
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  google-api-key: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.xaiApiKey }}
  xai-api-key: {{ .Values.secrets.xaiApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
