/**
 * BE1 — Task Groups v2 schema (task-groups-v2 §3).
 *
 * Insert-schema round-trip + enum acceptance/rejection + omit(id, createdAt) for
 * the new tables (task_group_iterations, task_executions) and the new label
 * column. Pure Zod-level assertions — no DB.
 */
import { describe, it, expect } from "vitest";
import {
  insertTaskGroupIterationSchema,
  insertTaskExecutionSchema,
  TASK_GROUP_STATUSES,
  TASK_STATUSES,
} from "@shared/schema";

describe("insertTaskGroupIterationSchema", () => {
  it("accepts a minimal valid iteration insert and omits id/createdAt", () => {
    const parsed = insertTaskGroupIterationSchema.safeParse({
      groupId: "g-1",
      iterationNumber: 1,
      input: "the prompt snapshot",
    });
    expect(parsed.success).toBe(true);
    // id and createdAt are NOT part of the insert shape (generated by the DB).
    expect("id" in (parsed.success ? parsed.data : {})).toBe(false);
    expect("createdAt" in (parsed.success ? parsed.data : {})).toBe(false);
  });

  it("accepts every TaskGroupStatus enum value for status", () => {
    for (const status of TASK_GROUP_STATUSES) {
      const parsed = insertTaskGroupIterationSchema.safeParse({
        groupId: "g-1",
        iterationNumber: 1,
        input: "x",
        status,
      });
      expect(parsed.success).toBe(true);
    }
  });

  it("rejects an out-of-enum status", () => {
    const parsed = insertTaskGroupIterationSchema.safeParse({
      groupId: "g-1",
      iterationNumber: 1,
      input: "x",
      status: "in_progress",
    });
    expect(parsed.success).toBe(false);
  });

  it("rejects a missing required field (input)", () => {
    const parsed = insertTaskGroupIterationSchema.safeParse({
      groupId: "g-1",
      iterationNumber: 1,
    });
    expect(parsed.success).toBe(false);
  });
});

describe("insertTaskExecutionSchema", () => {
  it("accepts a minimal valid execution insert and omits id/createdAt", () => {
    const parsed = insertTaskExecutionSchema.safeParse({
      iterationId: "it-1",
      taskId: "t-1",
      groupId: "g-1",
    });
    expect(parsed.success).toBe(true);
    expect("id" in (parsed.success ? parsed.data : {})).toBe(false);
    expect("createdAt" in (parsed.success ? parsed.data : {})).toBe(false);
  });

  it("accepts every TaskStatus enum value for status", () => {
    for (const status of TASK_STATUSES) {
      const parsed = insertTaskExecutionSchema.safeParse({
        iterationId: "it-1",
        taskId: "t-1",
        groupId: "g-1",
        status,
      });
      expect(parsed.success).toBe(true);
    }
  });

  it("rejects an out-of-enum status", () => {
    const parsed = insertTaskExecutionSchema.safeParse({
      iterationId: "it-1",
      taskId: "t-1",
      groupId: "g-1",
      status: "done",
    });
    expect(parsed.success).toBe(false);
  });

  it("rejects a missing mandatory scope key (groupId)", () => {
    const parsed = insertTaskExecutionSchema.safeParse({
      iterationId: "it-1",
      taskId: "t-1",
    });
    expect(parsed.success).toBe(false);
  });

  it("accepts artifacts and decisions jsonb payloads", () => {
    const parsed = insertTaskExecutionSchema.safeParse({
      iterationId: "it-1",
      taskId: "t-1",
      groupId: "g-1",
      artifacts: [{ kind: "file", path: "a.ts" }],
      decisions: ["chose plan A"],
      modelSlug: "claude-haiku-4-5",
    });
    expect(parsed.success).toBe(true);
  });
});
